octomap_server:
  ros__parameters:
    octomap_path: "/root/CrazySim/ros2_ws/src/icuas25_competition/worlds/city_1_small/meshes/city_1_small.binvox.bt"
    frame_id: "map"
    resolution: 0.05
    publish_free_space: false
    sensor_model:
      max_range: 5.0
      hit: 0.7
      miss: 0.4

    sensor_min_range: 0.0
    sensor_max_range: 5.0